use std::sync::Arc;

use handlebars::Handlebars;
use serde::Serialize;

use crate::helpers;

/// Errors that can occur during template operations.
#[derive(Debug, thiserror::Error)]
pub enum TemplateError {
    #[error("template not found: {0}")]
    NotFound(String),

    #[error("template render error: {0}")]
    Render(#[from] handlebars::RenderError),

    #[error("template registration error: {0}")]
    Registration(#[from] Box<handlebars::TemplateError>),
}

impl From<handlebars::TemplateError> for TemplateError {
    fn from(err: handlebars::TemplateError) -> Self {
        TemplateError::Registration(Box::new(err))
    }
}

/// A fully rendered email with subject, HTML body, and text body.
#[derive(Debug, Clone)]
pub struct RenderedEmail {
    pub subject: String,
    pub html: String,
    pub text: String,
}

/// Template engine with pre-loaded Handlebars templates.
#[derive(Clone)]
pub struct TemplateEngine {
    html_handlebars: Arc<Handlebars<'static>>,
    text_handlebars: Arc<Handlebars<'static>>,
}

impl std::fmt::Debug for TemplateEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("TemplateEngine").finish_non_exhaustive()
    }
}

impl TemplateEngine {
    /// Creates a builder for configuring the template engine.
    pub fn builder() -> TemplateEngineBuilder {
        TemplateEngineBuilder::new()
    }

    /// Renders a single named template with the given context data.
    /// Uses HTML escaping by default.
    pub fn render<T: Serialize>(
        &self,
        template_name: &str,
        data: &T,
    ) -> Result<String, TemplateError> {
        self.render_html(template_name, data)
    }

    /// Renders an event's subject, HTML body, and text body.
    ///
    /// Looks up `{event_name}/subject`, `{event_name}/body.html`, and
    /// `{event_name}/body.txt` templates. Subject and text body are rendered
    /// without HTML escaping.
    pub fn render_event<T: Serialize>(
        &self,
        event_name: &str,
        data: &T,
    ) -> Result<RenderedEmail, TemplateError> {
        let subject = self.render_text(&format!("{event_name}/subject"), data)?;
        let html = self.render_html(&format!("{event_name}/body.html"), data)?;
        let text = self.render_text(&format!("{event_name}/body.txt"), data)?;

        Ok(RenderedEmail {
            subject: subject.trim().to_string(),
            html,
            text,
        })
    }

    /// Returns a reference to the inner HTML Handlebars instance for advanced use.
    pub fn handlebars(&self) -> &Handlebars<'static> {
        &self.html_handlebars
    }

    fn render_html<T: Serialize>(
        &self,
        template_name: &str,
        data: &T,
    ) -> Result<String, TemplateError> {
        if !self.html_handlebars.has_template(template_name) {
            return Err(TemplateError::NotFound(template_name.to_string()));
        }
        Ok(self.html_handlebars.render(template_name, data)?)
    }

    fn render_text<T: Serialize>(
        &self,
        template_name: &str,
        data: &T,
    ) -> Result<String, TemplateError> {
        if !self.text_handlebars.has_template(template_name) {
            return Err(TemplateError::NotFound(template_name.to_string()));
        }
        Ok(self.text_handlebars.render(template_name, data)?)
    }
}

/// Builder for configuring and creating a [`TemplateEngine`].
pub struct TemplateEngineBuilder {
    handlebars: Handlebars<'static>,
    strict_mode: bool,
}

impl TemplateEngineBuilder {
    fn new() -> Self {
        let mut handlebars = Handlebars::new();
        handlebars.register_helper("default", Box::new(helpers::DefaultHelper));
        Self {
            handlebars,
            strict_mode: true,
        }
    }

    /// Registers all templates from an `EmailTemplate` enum generated by the
    /// derive macro. Call this for each template enum you want to use.
    pub fn register_templates<T>(mut self) -> Result<Self, TemplateError>
    where
        T: RegisterTemplates,
    {
        T::register(&mut self.handlebars)?;
        Ok(self)
    }

    /// Registers a Handlebars partial template (layout, component, etc.).
    pub fn register_partial(mut self, name: &str, template: &str) -> Result<Self, TemplateError> {
        self.handlebars.register_partial(name, template)?;
        Ok(self)
    }

    /// Disables strict mode (missing variables render as empty instead of
    /// erroring). Not recommended for production.
    pub fn lenient(mut self) -> Self {
        self.strict_mode = false;
        self
    }

    /// Registers a custom Handlebars helper function.
    pub fn register_helper(
        mut self,
        name: &str,
        helper: Box<dyn handlebars::HelperDef + Send + Sync>,
    ) -> Self {
        self.handlebars.register_helper(name, helper);
        self
    }

    /// Builds the template engine.
    pub fn build(mut self) -> Result<TemplateEngine, TemplateError> {
        self.handlebars.set_strict_mode(self.strict_mode);

        let mut text_handlebars = self.handlebars.clone();
        text_handlebars.register_escape_fn(handlebars::no_escape);

        Ok(TemplateEngine {
            html_handlebars: Arc::new(self.handlebars),
            text_handlebars: Arc::new(text_handlebars),
        })
    }
}

/// Trait implemented by `#[derive(EmailTemplate)]` enums to register their
/// templates into a Handlebars instance.
pub trait RegisterTemplates {
    fn register(handlebars: &mut Handlebars<'_>) -> Result<(), handlebars::TemplateError>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn build_engine_empty() {
        let engine = TemplateEngine::builder().build();
        assert!(engine.is_ok());
    }

    #[test]
    fn render_missing_template() {
        let engine = TemplateEngine::builder().build().unwrap();
        let result = engine.render("nonexistent", &json!({}));
        assert!(matches!(result, Err(TemplateError::NotFound(_))));
    }

    #[test]
    fn register_and_render_partial() {
        let engine = TemplateEngine::builder()
            .register_partial("greeting", "Hello {{name}}!")
            .unwrap()
            .lenient()
            .build()
            .unwrap();

        assert!(engine.handlebars().has_template("greeting"));
    }

    fn build_with_template(name: &str, source: &str) -> TemplateEngine {
        let mut hb = Handlebars::new();
        hb.register_helper("default", Box::new(helpers::DefaultHelper));
        hb.register_template_string(name, source).unwrap();

        let mut text_hb = hb.clone();
        text_hb.register_escape_fn(handlebars::no_escape);

        TemplateEngine {
            html_handlebars: Arc::new(hb),
            text_handlebars: Arc::new(text_hb),
        }
    }

    #[test]
    fn subject_not_html_escaped() {
        let engine = build_with_template("test/subject", "Hello {{name}}");
        let result = engine
            .render_text("test/subject", &json!({"name": "O'Brien <b>"}))
            .unwrap();
        assert_eq!(result, "Hello O'Brien <b>");
    }

    #[test]
    fn html_body_is_escaped() {
        let engine = build_with_template("test/body.html", "<p>{{name}}</p>");
        let result = engine
            .render_html(
                "test/body.html",
                &json!({"name": "<script>alert(1)</script>"}),
            )
            .unwrap();
        assert!(result.contains("&lt;script&gt;"));
    }

    #[test]
    fn default_helper_escapes_in_html() {
        let engine = build_with_template("test", "{{default name \"fallback\"}}");
        let result = engine
            .render_html("test", &json!({"name": "<script>x</script>"}))
            .unwrap();
        assert!(!result.contains("<script>"));
    }

    #[test]
    fn default_helper_no_escape_in_text() {
        let engine = build_with_template("test", "{{default name \"fallback\"}}");
        let result = engine
            .render_text("test", &json!({"name": "<script>x</script>"}))
            .unwrap();
        assert_eq!(result, "<script>x</script>");
    }

    #[test]
    fn default_helper_uses_fallback() {
        let engine = build_with_template("test", "{{default name \"there\"}}");
        let result = engine.render_html("test", &json!({})).unwrap();
        assert_eq!(result, "there");
    }

    #[test]
    fn default_helper_zero_is_falsy() {
        let engine = build_with_template("test", "{{default n \"fb\"}}");
        let result = engine.render_html("test", &json!({"n": 0})).unwrap();
        assert_eq!(result, "fb");
    }

    #[test]
    fn user_helper_not_overwritten() {
        use handlebars::{Context, Helper, Output, RenderContext};

        fn custom_default(
            _: &Helper,
            _: &Handlebars,
            _: &Context,
            _: &mut RenderContext,
            out: &mut dyn Output,
        ) -> handlebars::HelperResult {
            out.write("CUSTOM")?;
            Ok(())
        }

        let engine = TemplateEngine::builder()
            .register_helper("default", Box::new(custom_default))
            .register_partial("test", "{{default name \"there\"}}")
            .unwrap()
            .lenient()
            .build()
            .unwrap();

        let result = engine.render("test", &json!({"name": "Alice"})).unwrap();
        assert_eq!(result, "CUSTOM");
    }

    #[test]
    fn builtin_and_or_eq_ne_work() {
        let engine = build_with_template("test_and", "{{#if (and a b c)}}T{{else}}F{{/if}}");
        let result = engine
            .render_html("test_and", &json!({"a": true, "b": true, "c": false}))
            .unwrap();
        assert_eq!(result, "F");

        let engine = build_with_template("test_eq", "{{#if (eq x y)}}T{{else}}F{{/if}}");
        let result = engine
            .render_html("test_eq", &json!({"x": "a", "y": "a"}))
            .unwrap();
        assert_eq!(result, "T");
    }

    fn build_with_event(slug: &str, subject: &str, html: &str, txt: &str) -> TemplateEngine {
        let mut hb = Handlebars::new();
        hb.register_helper("default", Box::new(helpers::DefaultHelper));
        hb.register_template_string(&format!("{slug}/subject"), subject)
            .unwrap();
        hb.register_template_string(&format!("{slug}/body.html"), html)
            .unwrap();
        hb.register_template_string(&format!("{slug}/body.txt"), txt)
            .unwrap();

        let mut text_hb = hb.clone();
        text_hb.register_escape_fn(handlebars::no_escape);

        TemplateEngine {
            html_handlebars: Arc::new(hb),
            text_handlebars: Arc::new(text_hb),
        }
    }

    #[test]
    fn render_event_renders_all_parts() {
        let engine = build_with_event(
            "welcome",
            "Hi {{name}}",
            "<h1>Hello {{name}}</h1>",
            "Hello {{name}}",
        );
        let rendered = engine
            .render_event("welcome", &json!({"name": "Alice"}))
            .unwrap();
        assert_eq!(rendered.subject, "Hi Alice");
        assert_eq!(rendered.html, "<h1>Hello Alice</h1>");
        assert_eq!(rendered.text, "Hello Alice");
    }

    #[test]
    fn render_event_trims_subject_whitespace() {
        let engine = build_with_event("ev", "  Hello {{name}}  \n", "<p>X</p>", "X");
        let rendered = engine.render_event("ev", &json!({"name": "Bob"})).unwrap();
        assert_eq!(rendered.subject, "Hello Bob");
    }

    #[test]
    fn render_event_missing_subject_template() {
        let engine = build_with_template("ev/body.html", "<p>X</p>");
        let result = engine.render_event("ev", &json!({}));
        assert!(matches!(result, Err(TemplateError::NotFound(ref s)) if s == "ev/subject"));
    }

    #[test]
    fn render_event_missing_html_template() {
        let hb = Handlebars::new();

        let mut text_hb = Handlebars::new();
        text_hb.register_escape_fn(handlebars::no_escape);
        text_hb
            .register_template_string("ev/subject", "Sub")
            .unwrap();
        text_hb
            .register_template_string("ev/body.txt", "Text")
            .unwrap();

        let engine = TemplateEngine {
            html_handlebars: Arc::new(hb),
            text_handlebars: Arc::new(text_hb),
        };
        let result = engine.render_event("ev", &json!({}));
        assert!(matches!(result, Err(TemplateError::NotFound(ref s)) if s == "ev/body.html"));
    }

    #[test]
    fn render_event_missing_txt_template() {
        let mut hb = Handlebars::new();
        hb.register_template_string("ev/body.html", "<p>Html</p>")
            .unwrap();

        let mut text_hb = Handlebars::new();
        text_hb.register_escape_fn(handlebars::no_escape);
        text_hb
            .register_template_string("ev/subject", "Sub")
            .unwrap();

        let engine = TemplateEngine {
            html_handlebars: Arc::new(hb),
            text_handlebars: Arc::new(text_hb),
        };
        let result = engine.render_event("ev", &json!({}));
        assert!(matches!(result, Err(TemplateError::NotFound(ref s)) if s == "ev/body.txt"));
    }

    #[test]
    fn strict_mode_rejects_missing_variable() {
        let engine = TemplateEngine::builder()
            .register_partial("test", "Hello {{name}}")
            .unwrap()
            .build()
            .unwrap();
        let result = engine.render("test", &json!({}));
        assert!(matches!(result, Err(TemplateError::Render(_))));
    }

    #[test]
    fn lenient_mode_allows_missing_variable() {
        let engine = TemplateEngine::builder()
            .register_partial("test", "Hello {{name}}")
            .unwrap()
            .lenient()
            .build()
            .unwrap();
        let result = engine.render("test", &json!({})).unwrap();
        assert_eq!(result, "Hello ");
    }

    #[test]
    fn render_method_uses_html_escaping() {
        let engine = build_with_template("test", "<p>{{content}}</p>");
        let result = engine
            .render("test", &json!({"content": "<b>bold</b>"}))
            .unwrap();
        assert!(result.contains("&lt;b&gt;"));
        assert!(!result.contains("<b>bold</b>"));
    }

    #[test]
    fn render_event_html_escapes_text_does_not() {
        let engine = build_with_event("ev", "{{title}}", "<p>{{content}}</p>", "{{content}}");
        let data = json!({"title": "A & B", "content": "<script>alert(1)</script>"});
        let rendered = engine.render_event("ev", &data).unwrap();

        assert_eq!(rendered.subject, "A & B");
        assert!(rendered.html.contains("&lt;script&gt;"));
        assert!(rendered.text.contains("<script>alert(1)</script>"));
    }

    #[test]
    fn partial_used_inside_template() {
        let engine = TemplateEngine::builder()
            .register_partial("header", "<h1>{{title}}</h1>")
            .unwrap()
            .register_partial("page", "{{> header}}<p>body</p>")
            .unwrap()
            .lenient()
            .build()
            .unwrap();
        let result = engine.render("page", &json!({"title": "Hi"})).unwrap();
        assert_eq!(result, "<h1>Hi</h1><p>body</p>");
    }

    #[test]
    fn register_invalid_template_returns_error() {
        let result = TemplateEngine::builder().register_partial("bad", "{{#if}}");
        assert!(result.is_err());
    }
}
